name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check
        run: |
          echo OK!

  version:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Check if version is same as tag
        run: |
          echo "ref_name=${{ github.ref_name }}"
