name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  checkA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Erlang/OTP
        uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1.18.2
        with:
          otp-version: '27.1.2'
          rebar3-version: '3.23.0'
      - name: Check
        run: |
          echo rebar3 shell --apps myapp --eval \
          '{ok, Version} = application:get_key(myapp, vsn), case Version of "${{ github.ref_name }}" -> halt(0,[]); _ -> halt(1,[]) end.'
  checkB:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Erlang/OTP
        uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1.18.2
        with:
          otp-version: '27.1.2'
          rebar3-version: '3.23.0'
      - name: Check
        run: |
          rebar3 shell --apps myapp --eval \
          '{ok, Version} = application:get_key(myapp, vsn), case Version of "${{ github.ref_name }}" -> halt(0,[]); _ -> halt(1,[]) end.'
  checkC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Erlang/OTP
        uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1.18.2
        with:
          otp-version: '27.1.2'
          rebar3-version: '3.23.0'
      - name: Check
        run: |
          CMD=$(cat << EOF
          {ok, Version} = application:get_key(myapp, vsn),
          case Version of
              "${{ github.ref_name }}" ->
                  halt(0,[]);
              _ ->
                  halt(1,[])
          end.
          EOF)
          echo $CMD
          rebar3 shell --apps myapp --eval $CMD
  checkD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Erlang/OTP
        uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1.18.2
        with:
          otp-version: '27.1.2'
          rebar3-version: '3.23.0'
      - name: Check
        run: |
          rebar3 shell --apps myapp --eval $(cat << EOF
          Version = ${{ github.ref_name }},
          case application:get_key(myapp, vsn) of
              {ok, Version} ->
                  halt(0,[]);
              _ ->
                  halt(1,[])
          end.
          EOF)
